export const productCatalog = [
  {
    slug: "tidytree",
    name: "TidyTree.ai",
    zhTagline: "组织架构一变，权限与汇报链自动同步",
    enTagline: "Auto-sync org charts, permissions, and reporting lines",
    zhPain: "你是否在为繁琐的部门变动调整耗费心神？",
    enPain: "Are department changes draining your team every week?",
    zhOverview:
      "当组织调整发生，TidyTree 自动更新组织架构、权限继承与汇报链，不再依赖 Excel 手工维护。",
    enOverview:
      "When org changes happen, TidyTree updates structure, permissions, and reporting chains automatically.",
    zhHighlights: [
      "可视化组织树自动生成与版本追踪",
      "部门调整后自动触发权限变更",
      "跨系统同步汇报链与审批路径",
    ],
    enHighlights: [
      "Auto-generated visual org tree with version tracking",
      "Permission updates after department changes",
      "Cross-system sync of reporting and approval paths",
    ],
    zhWorkflow: ["录制部门调整动作", "AI 学习组织规则", "自动执行权限与流程同步"],
    enWorkflow: ["Record re-org operation", "AI learns org rules", "Auto-sync permissions and workflows"],
    metrics: [
      { value: "60%", labelZh: "组织调整效率提升", labelEn: "Faster re-org execution" },
      { value: "90%", labelZh: "人工录入减少", labelEn: "Less manual input" },
      { value: "99.5%", labelZh: "同步准确率", labelEn: "Sync accuracy" },
    ],
    price: "¥39,800 / 年",
  },
  {
    slug: "tidyokr",
    name: "TidyOKR.ai",
    zhTagline: "OKR 拆解到执行，自动追踪目标进度",
    enTagline: "From strategy to execution with auto OKR tracking",
    zhPain: "季度 OKR 追踪靠表格，更新慢且不统一。",
    enPain: "OKR updates are fragmented across spreadsheets.",
    zhOverview: "自动收集进展、识别风险并生成周报，让管理层聚焦决策。",
    enOverview: "Auto-collect progress, detect risks, and generate weekly updates for leaders.",
    zhHighlights: ["目标拆解建议", "关键结果自动采集", "风险预警提示"],
    enHighlights: ["Goal decomposition assistant", "KR auto collection", "Risk alerts"],
    zhWorkflow: ["定义组织目标", "AI 连接执行系统", "自动生成 OKR 看板"],
    enWorkflow: ["Define company goals", "AI connects execution systems", "Live OKR board generated"],
    metrics: [
      { value: "55%", labelZh: "OKR 对齐效率提升", labelEn: "Faster OKR alignment" },
      { value: "4x", labelZh: "周报生成速度", labelEn: "Faster status reporting" },
      { value: "30%", labelZh: "目标偏差下降", labelEn: "Reduced target drift" },
    ],
    price: "¥32,800 / 年",
  },
  {
    slug: "tidykpi",
    name: "TidyKPI.ai",
    zhTagline: "绩效指标实时更新，经营状态随时可见",
    enTagline: "Real-time KPI intelligence for management",
    zhPain: "绩效数据分散在多个系统，统计慢且误差高。",
    enPain: "KPI metrics are scattered and delayed.",
    zhOverview: "自动抓取核心指标并生成可视化看板与偏差解释。",
    enOverview: "Collect KPI data across systems and present visualized insights.",
    zhHighlights: ["跨系统 KPI 汇聚", "异常波动诊断", "经营日报自动推送"],
    enHighlights: ["Cross-system KPI aggregation", "Anomaly diagnosis", "Auto operation digest"],
    zhWorkflow: ["配置指标口径", "连接业务系统", "AI 自动汇总与分析"],
    enWorkflow: ["Set KPI definitions", "Connect business systems", "AI summarizes and analyzes"],
    metrics: [
      { value: "70%", labelZh: "报表时间减少", labelEn: "Less reporting time" },
      { value: "88%", labelZh: "异常识别命中率", labelEn: "Anomaly detection precision" },
      { value: "24h", labelZh: "日报自动生成周期", labelEn: "Daily digest cadence" },
    ],
    price: "¥29,800 / 年",
  },
  {
    slug: "tidyorg",
    name: "TidyOrg.ai",
    zhTagline: "组织动作统一编排，管理动作可追踪",
    enTagline: "Orchestrate organization actions with full traceability",
    zhPain: "组织动作分散，流程依赖人工协调。",
    enPain: "Organization changes rely on manual handoffs.",
    zhOverview: "将任命、调岗、协同流程标准化并自动执行。",
    enOverview: "Standardize and automate assignment, transfer, and collaboration flows.",
    zhHighlights: ["流程编排模板", "关键节点提醒", "执行日志审计"],
    enHighlights: ["Flow templates", "Critical node reminders", "Execution audit logs"],
    zhWorkflow: ["选择组织动作模板", "配置审批策略", "自动触发执行与回执"],
    enWorkflow: ["Select organization template", "Set approval policy", "Automate execution and receipts"],
    metrics: [
      { value: "50%", labelZh: "跨部门协作耗时下降", labelEn: "Less cross-team friction" },
      { value: "95%", labelZh: "流程节点可追踪率", labelEn: "Traceable process coverage" },
      { value: "3x", labelZh: "执行效率提升", labelEn: "Execution speedup" },
    ],
    price: "¥28,800 / 年",
  },
  {
    slug: "tidykanban",
    name: "TidyKanban.ai",
    zhTagline: "研发任务流自动推进，交付状态实时更新",
    enTagline: "AI-driven project board automation for R&D teams",
    zhPain: "研发看板维护繁琐，状态更新滞后。",
    enPain: "Engineering board updates are manual and stale.",
    zhOverview: "自动根据提交、测试与发布状态更新任务流。",
    enOverview: "Automatically update task stages from commit, test, and release signals.",
    zhHighlights: ["任务状态自动迁移", "阻塞原因识别", "里程碑预测"],
    enHighlights: ["Auto stage transitions", "Blocker detection", "Milestone forecasting"],
    zhWorkflow: ["配置研发流程", "接入项目工具", "AI 自动维护看板"],
    enWorkflow: ["Define dev workflow", "Connect project tools", "AI maintains board"],
    metrics: [
      { value: "62%", labelZh: "看板维护工作减少", labelEn: "Less board maintenance" },
      { value: "42%", labelZh: "延期风险下降", labelEn: "Lower delay risk" },
      { value: "2x", labelZh: "项目透明度提升", labelEn: "Higher delivery visibility" },
    ],
    price: "¥35,800 / 年",
  },
  {
    slug: "tidyproduct",
    name: "TidyProduct.ai",
    zhTagline: "需求到上线，全链路产品流程智能化",
    enTagline: "AI copiloting product lifecycle from idea to release",
    zhPain: "需求评审与跨部门沟通成本高。",
    enPain: "Product reviews and collaboration are slow and costly.",
    zhOverview: "自动生成需求摘要、任务拆解和上线检查清单。",
    enOverview: "Generate requirement summaries, task breakdowns, and release checklists.",
    zhHighlights: ["需求智能归类", "评审纪要自动整理", "发布质量门控"],
    enHighlights: ["Smart requirement clustering", "Auto review notes", "Release quality gates"],
    zhWorkflow: ["收集需求输入", "AI 分析与拆解", "推送到研发执行系统"],
    enWorkflow: ["Collect requirement input", "AI analyzes and decomposes", "Push to execution tools"],
    metrics: [
      { value: "48%", labelZh: "需求处理周期下降", labelEn: "Shorter requirement cycle" },
      { value: "75%", labelZh: "评审记录自动化", labelEn: "Automated review documentation" },
      { value: "35%", labelZh: "需求返工减少", labelEn: "Less rework" },
    ],
    price: "¥34,800 / 年",
  },
  {
    slug: "tidyflows",
    name: "TidyFlows.ai",
    zhTagline: "业务流程智能编排，跨部门自动流转",
    enTagline: "No-code AI flow orchestration across departments",
    zhPain: "跨团队流程多环节手工交接，错误率高。",
    enPain: "Cross-team processes involve manual handoffs and errors.",
    zhOverview: "用演示动作训练 AI，自动执行复杂跨系统流程。",
    enOverview: "Train AI with demonstrations to automate complex cross-system flows.",
    zhHighlights: ["无代码流程搭建", "跨系统节点执行", "回滚与异常处理"],
    enHighlights: ["No-code flow builder", "Cross-system task execution", "Rollback and exception handling"],
    zhWorkflow: ["录制流程动作", "设置触发条件", "AI 自动执行与反馈"],
    enWorkflow: ["Record process actions", "Set trigger conditions", "AI executes and reports"],
    metrics: [
      { value: "68%", labelZh: "流程交付提速", labelEn: "Faster process delivery" },
      { value: "85%", labelZh: "流程自动化覆盖", labelEn: "Automation coverage" },
      { value: "40%", labelZh: "运营差错下降", labelEn: "Lower ops errors" },
    ],
    price: "¥31,800 / 年",
  },
  {
    slug: "tidyclaw",
    name: "TidyClaw.ai",
    zhTagline: "为老旧系统装上 AI 手臂，无需 API",
    enTagline: "Give legacy systems an AI robotic arm, no API required",
    zhPain: "老系统无 API，重复录入耗时且易错。",
    enPain: "Legacy systems without APIs force repetitive manual entry.",
    zhOverview:
      "无论是 ERP、财务系统还是十年前的后台，TidyClaw 通过视觉识别完成跨系统操作。",
    enOverview:
      "From ERP to decade-old back offices, TidyClaw uses visual recognition for cross-system actions.",
    zhHighlights: ["视觉识别定位控件", "模拟人工操作录入", "跨系统任务串联"],
    enHighlights: ["Visual control recognition", "Human-like operation simulation", "Cross-system task chaining"],
    zhWorkflow: ["录制界面操作", "AI 识别字段与步骤", "按策略自动执行"],
    enWorkflow: ["Record UI actions", "AI maps fields and steps", "Automated policy-based execution"],
    metrics: [
      { value: "90%", labelZh: "人工录入减少", labelEn: "Less manual entry" },
      { value: "4x", labelZh: "跨系统执行速度", labelEn: "Faster cross-system execution" },
      { value: "97%", labelZh: "动作稳定成功率", labelEn: "Execution success rate" },
    ],
    price: "¥37,800 / 年",
  },
  {
    slug: "tidyagent",
    name: "TidyAgent.ai",
    zhTagline: "企业级 AI 智能体中枢，统一调度全流程",
    enTagline: "Enterprise agent hub for orchestrating all automations",
    zhPain: "AI 工具分散，缺乏统一治理与运营。",
    enPain: "AI tools are fragmented with limited governance.",
    zhOverview: "统一策略、权限与监控，管理所有 Tidy 组件。",
    enOverview: "Centralize policy, access, and observability for all Tidy modules.",
    zhHighlights: ["智能体编排中心", "权限策略管理", "企业级可观测性"],
    enHighlights: ["Agent orchestration hub", "Policy and access control", "Enterprise observability"],
    zhWorkflow: ["接入各业务模块", "配置治理策略", "统一监控与优化"],
    enWorkflow: ["Integrate business modules", "Configure governance policy", "Monitor and optimize centrally"],
    metrics: [
      { value: "80%", labelZh: "运维协同效率提升", labelEn: "Higher ops efficiency" },
      { value: "100%", labelZh: "模块统一治理覆盖", labelEn: "Governance coverage" },
      { value: "35%", labelZh: "平台运维成本下降", labelEn: "Lower platform cost" },
    ],
    price: "¥45,800 / 年",
  },
];

export const solutionBundles = [
  {
    key: "rd",
    titleZh: "研发团队方案",
    titleEn: "R&D Team Stack",
    descZh: "将需求、任务、进度和自动执行串成闭环，缩短研发交付周期。",
    descEn: "Connect product planning, execution, and automation into one delivery loop.",
    modules: ["TidyKanban.ai", "TidyProduct.ai", "TidyAgent.ai"],
  },
  {
    key: "hr",
    titleZh: "HR 与管理层方案",
    titleEn: "HR & Leadership Stack",
    descZh: "组织管理、绩效与目标统一管理，让组织动作实时可见。",
    descEn: "Unify organization design, KPI, and OKR for leadership visibility.",
    modules: ["TidyOrg.ai", "TidyTree.ai", "TidyKPI.ai", "TidyOKR.ai"],
  },
  {
    key: "ops",
    titleZh: "运营与后台方案",
    titleEn: "Operations & Back-office Stack",
    descZh: "跨系统流程自动执行，老旧系统也能直接接入 AI 自动化。",
    descEn: "Automate cross-system execution and modernize legacy back-office tools.",
    modules: ["TidyFlows.ai", "TidyClaw.ai"],
  },
];
